version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=todo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  nats:
    image: nats:2-alpine
    ports:
      - "8222:8222"
      - "4222:4222"

volumes:
  mongo-data:
    driver: local
